# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: vsrmmt123
# "service" is the name of this project. This will also be added to your AWS resource names.
service: lambda-eventbg

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: DEV

custom: ${file(./custom.yml):${self:provider.stage}}

resources:
  Resources:
    MyNewCustomEventBus:
      Type: AWS::Events::EventBus
      Properties:
        Name: MyNewCustomEventBus
    
    Rule897ca662:
      Type: AWS::Events::Rule
      Properties:
        Name: MyNewCustomEventBus-same-acc-rule2
        EventPattern:
          source:
            - NPS
          detail-type:
            - nps-kiosk
            - nps-order-ahead
        State: ENABLED
        EventBusName: MyNewCustomEventBus
        Targets:
          - Id: Id77a8ee67-2eed-4ff2-a138-e117c27e2ce3
            Arn: !Sub arn:aws:events:${AWS::Region}:${self:custom.receiverEbAWSAccount}:event-bus/my-receiver-eb
            RoleArn: !GetAtt Rolecde16c2f.Arn
              
    Rolecde16c2f:
      Type: AWS::IAM::Role
      Properties:
        RoleName: vsr-same-acc-eb-role
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service: events.amazonaws.com
              Action: sts:AssumeRole

    Policy4a9add9b:
      Type: AWS::IAM::RolePolicy
      Properties:
        PolicyName: vsr-same-acc-eb-role-policy
        RoleName: !Ref Rolecde16c2f
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Sid: ActionsForResource
              Effect: Allow
              Action:
                - events:PutEvents
              Resource: !Sub arn:aws:events:${AWS::Region}:${self:custom.receiverEbAWSAccount}:event-bus/my-receiver-eb

plugins:
  - serverless-offline
